apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  labels:
    app: my-application
spec:
  containers:
    - name: nginx-container
      image: nginx:latest
      imagePullPolicy: IfNotPresent
      ports:
        - name: http
          containerPort: 80
          protocol: TCP
  restartPolicy: Always
  